### ISSUE TITLE
Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by lexrus** [zhxnlai/Algorithms#5]
https://github.com/zhxnlai/Algorithms/blob/master/swift/Remove%20Duplicates%20from%20Sorted%20Array.playground/section-1.swift#L13

While the problem is "remove the duplicates __in place__", you have to deal with the original array. I think it's impossible to achieve this requirement in Swift 1.2 because of the immutability of Array object. Perhaps NSMutableArray is the right workaround?

Any advice?

**Comment by lexrus** [comment]
Please check out my answer:
https://github.com/lexrus/LeetCode.swift/blob/master/RemoveDuplicatesFromSortedArray/RemoveDuplicatesFromSortedArray.swift

**Comment by zhxnlai** [comment]
I believe you can modify a function parameter using the `inout` keyword. I just updated the example [here](https://github.com/zhxnlai/Algorithms/blob/cc78ac5f2342673e0c08222345b40ebe4df491e5/swift/Remove%20Duplicates%20from%20Sorted%20Array.playground/Contents.swift#L45).

**Comment by lexrus** [comment]
Thanks. You are right.
But is it possible to write an extension for Array?

``` swift
extension Array {
    mutating func removeDuplicates() -> Int {
       ???
    }
}
```

**Comment by zhxnlai** [comment]
I tried this

``` swift
extension Array {
    mutating func removeDuplicates() -> Int {
        var index = 0

        for var i=0; i<self.count; i++ {
            if (self[i] != self[index]) {
                index++
                self[index] = self[i]
            }
        }

        self.removeRange(index+1..<self.count)
        return self.count
    }
}
```

but the compiler complains about this line of code

``` swift
            if (self[i] != self[index]) {
```

becuase `!=` operator only works with objects that implements `Equatable` protocol. Since Array is generic, there is no such guarantee.

I cannot think of a way to add a function to `Array` (or any generic types) but only for selected types (special cases).

**Comment by lexrus** [comment]
Thanks a lot.
